"""add_status_to_industry_experts

Revision ID: c0b1dec9a095
Revises: 4c2ceff9e65a
Create Date: 2026-09-10 15:33:16.527726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0b1dec9a095'
down_revision = '4c2ceff9e65a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('industry_experts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))
        batch_op.create_index(batch_op.f('ix_industry_experts_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('industry_experts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_industry_experts_status'))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
